floodSite/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from machina.app import board
from rest_framework import routers
from api import views
from pusherchat import views as chatviews
from pusherchat2 import views as chatviews2
from pusherchat3 import views as chatviews3


router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'groups', views.GroupViewSet)
router.register(r'myprofiles', views.MyProfileViewSet)
router.register(r'todos', views.TodoViewSet)

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('home.urls', namespace='home')),
    url(r'^', include('dashboard.urls')),
    url(r'^forum/', include(board.urls)),
    # url(r'^schedule/', include('schedule.urls')),
    url(r'^', include('todoList.urls')),
    url(r'^', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^chat/', chatviews.chat),
    url(r'^ajax/chat/$', chatviews.broadcast),
    url(r'^chat2/', chatviews2.chat),
    url(r'^ajax/chat2/$', chatviews2.broadcast),
    url(r'^chat3/', chatviews3.chat),
    url(r'^ajax/chat3/$', chatviews3.broadcast),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# this static thing is only for development, not production

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document=settings.MEDIA_ROOT)

home/urls.py
from django.conf.urls import url, include
from home import views
from home.regbackend import MyRegistrationView
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views
from django.core.urlresolvers import reverse_lazy
from machina.app import board


urlpatterns = [
    url(r'^$', views.home, name="home"),
    url(r'^accounts/register/$', MyRegistrationView.as_view(),name='registration_register'),
    url(r'^register/closed/$', TemplateView.as_view(template_name='registration/registration_closed.html'),name='registration_disallowed'),
    url(r'^accounts/', include('registration.backends.simple.urls'), name="register"),
    url(r'^privacy_policy/$', views.privacy_policy.as_view(), name="privacy_policy"),
    url(r'^password_reset/$', auth_views.PasswordResetView.as_view(success_url=reverse_lazy('home:password_reset_done'), template_name='registration/password_reset_form.html'),name='password_reset'),
    url(r'^password_reset/done/$', auth_views.PasswordResetDoneView.as_view(),name='password_reset_done'),
     url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html',success_url=reverse_lazy('home:password_reset_complete')), name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'), name='password_reset_complete'),

]

schedule/urls.py
from django.conf.urls import url
from django.views.generic.list import ListView
from schedule.models import Calendar
from schedule.feeds import UpcomingEventsFeed
from schedule.feeds import CalendarICalendar
from schedule.periods import Year, Month, Week, Day
from schedule.views import (
    CalendarByPeriodsView, CalendarView, EventView,
    OccurrenceView, EditOccurrenceView, DeleteEventView,
    EditEventView, CreateEventView, OccurrencePreview,
    CreateOccurrenceView, CancelOccurrenceView, FullCalendarView,
    api_select_create, api_move_or_resize_by_code, api_occurrences)

urlpatterns = [
    url(r'^$', ListView.as_view(model=Calendar), name='calendar_list'),

    url(r'^calendar/year/(?P<calendar_slug>[-\w]+)/$',
        CalendarByPeriodsView.as_view(template_name='schedule/calendar_year.html'),
        name='year_calendar',
        kwargs={'period': Year}),

    url(r'^calendar/tri_month/(?P<calendar_slug>[-\w]+)/$',
        CalendarByPeriodsView.as_view(template_name='schedule/calendar_tri_month.html'),
        name='tri_month_calendar',
        kwargs={'period': Month}),

    url(r'^calendar/compact_month/(?P<calendar_slug>[-\w]+)/$',
        CalendarByPeriodsView.as_view(template_name='schedule/calendar_compact_month.html'),
        name='compact_calendar',
        kwargs={'period': Month}),

    url(r'^calendar/month/(?P<calendar_slug>[-\w]+)/$',
        CalendarByPeriodsView.as_view(template_name='schedule/calendar_month.html'),
        name='month_calendar',
        kwargs={'period': Month}),

    url(r'^calendar/week/(?P<calendar_slug>[-\w]+)/$',
        CalendarByPeriodsView.as_view(template_name='schedule/calendar_week.html'),
        name='week_calendar',
        kwargs={'period': Week}),

    url(r'^calendar/daily/(?P<calendar_slug>[-\w]+)/$',
        CalendarByPeriodsView.as_view(template_name='schedule/calendar_day.html'),
        name='day_calendar',
        kwargs={'period': Day}),

    url(r'^calendar/(?P<calendar_slug>[-\w]+)/$',
        CalendarView.as_view(),
        name='calendar_home',
        ),
    url(r'^fullcalendar/(?P<calendar_slug>[-\w]+)/$',
        FullCalendarView.as_view(),
        name='fullcalendar'),

    # Event Urls
    url(r'^event/create/(?P<calendar_slug>[-\w]+)/$',
        CreateEventView.as_view(),
        name='calendar_create_event'),
    url(r'^event/edit/(?P<calendar_slug>[-\w]+)/(?P<event_id>\d+)/$',
        EditEventView.as_view(),
        name='edit_event'),
    url(r'^event/(?P<event_id>\d+)/$',
        EventView.as_view(),
        name='event'),
    url(r'^event/delete/(?P<event_id>\d+)/$',
        DeleteEventView.as_view(),
        name='delete_event'),

    # urls for already persisted occurrences
    url(r'^occurrence/(?P<event_id>\d+)/(?P<occurrence_id>\d+)/$',
        OccurrenceView.as_view(),
        name='occurrence'),
    url(r'^occurrence/cancel/(?P<event_id>\d+)/(?P<occurrence_id>\d+)/$',
        CancelOccurrenceView.as_view(),
        name='cancel_occurrence'),
    url(r'^occurrence/edit/(?P<event_id>\d+)/(?P<occurrence_id>\d+)/$',
        EditOccurrenceView.as_view(),
        name='edit_occurrence'),

    # urls for unpersisted occurrences
    url(r'^occurrence/(?P<event_id>\d+)/(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/(?P<hour>\d+)/(?P<minute>\d+)/(?P<second>\d+)/$',
        OccurrencePreview.as_view(),
        name='occurrence_by_date'),
    url(r'^occurrence/cancel/(?P<event_id>\d+)/(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/(?P<hour>\d+)/(?P<minute>\d+)/(?P<second>\d+)/$',
        CancelOccurrenceView.as_view(),
        name='cancel_occurrence_by_date'),
    url(r'^occurrence/edit/(?P<event_id>\d+)/(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/(?P<hour>\d+)/(?P<minute>\d+)/(?P<second>\d+)/$',
        CreateOccurrenceView.as_view(),
        name='edit_occurrence_by_date'),

    # feed urls
    url(r'^feed/calendar/upcoming/(?P<calendar_id>\d+)/$', UpcomingEventsFeed(), name='upcoming_events_feed'),
    url(r'^ical/calendar/(.*)/$', CalendarICalendar(), name='calendar_ical'),

    # api urls
    url(r'^api/occurrences', api_occurrences, name='api_occurences'),
    url(r'^api/move_or_resize/$',
        api_move_or_resize_by_code,
        name='api_move_or_resize'),
    url(r'^api/select_create/$',
        api_select_create,
        name='api_select_create'),
]

templates/forum_base.html
{% load i18n %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    {% block head %}
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, maximum-scale=1.0">

    <title>{% block title %}{{ site.name }}{% endblock %}</title>


    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
        <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    {% endblock head %}

    {% block css %}
    {% endblock css %}

    {% block extra_css %}
    <link href="https://fonts.googleapis.com/css?family=Amatic+SC:700|Arima+Madurai|Bungee+Inline|Copse|Josefin+Slab:600|Sanchez" rel="stylesheet">
     <link rel="stylesheet" href="{% static 'index_css/style_forum.css' %}"/>
{#     <link href="https://fonts.googleapis.com/css?family=Bungee+Shade|Amatic+SC:700|#}
{#     Josefin+Slab:600|Copse|Sanchez|Arima+Madurai" rel="stylesheet">#}
{#     <link href="https://fonts.googleapis.com/css?family=Amatic+SC:700" rel="stylesheet">#}
    {% endblock extra_css %}

  </head>
  <body>
    {% block js %}
    {% endblock js %}

    {% block body %}
      {# The forum content will go in this 'body' block #}
    {% endblock body %}

    {% block extra_js %}
    <script>
        $(".navbar-brand").html("<img style='width: 30px; height: 30px;' src='{% static "media/logo_2.png" %}'>");
        {% if request.user.is_authenticated %}
{#            var div = $("<div id='sidenav'></div>").addClass("col-sm-7 col-md-8 col-lg-5");#}
            $("<ul class='nav navbar-nav navbar-right'><li><a>Hello, {{ request.user }} !</a></li><li><a href= '{% url 'dashboard' %}'>Dashboard</a></li> <li><a href='/accounts/logout/'>Logout</a></li></ul>").appendTo(".collapse.navbar-collapse");
{#            $(div).appendTo(".collapse.navbar-collapse");#}
        {% endif %}
    </script>
    {% endblock extra_js %}
  </body>
</html>

templates/head_css.html
{% load static %}
<link href="https://fonts.googleapis.com/css?family=Amatic+SC:700|Arima+Madurai|Bungee+Inline|Copse|Josefin+Slab:600|Sanchez" rel="stylesheet">
<link rel="stylesheet" href="{% static 'index_css/style_home.css' %}">
<!--bootstrap css-->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

templates/javascript.html
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

templates/navbar.html
{% load static %}
<nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'home:home' %}"><img style="width: 30px; height: 30px;" src="{% static 'media/logo_2.png' %}"></a>

        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
          <ul class="nav navbar-nav">
            <li class="active"><a href="{% url 'home:home' %}">Home</a></li>
            {% if request.path == "/" %}
                <li><a href="#about">About</a></li>
                <li><a href="#contact">Contact</a></li>
                <li><a href="#privacy">Privacy Policy</a></li>
                <li><a href="{% url 'forum:index' %}">Forum</a></li>
                
                <li><div class="dropdown">
                  <button class="btn" type="button" data-toggle="dropdown" style="height: 50px">Chatrooms
                  <span class="caret"></span></button>
                  <ul class="dropdown-menu">
                    <li><a href= "/chat/">General</a></li>
                    <li><a href= "/chat2/">Environmental</a></li>
                    <li><a href= "/chat3/">Motivational</a></li>
                  </ul>
                </div>
              </li>
              {% endif %}

          </ul>
          <ul class="nav navbar-nav navbar-right">
              {% if request.user.is_authenticated %}
              <li><a href= "{% url 'profile' %}">Hello, {{ request.user }} !</a></li>
              <li><a href= "{% url 'dashboard' %}">Dashboard</a></li>
              <li><a href= "/accounts/logout/">Logout</a></li>
              {% else %}
              <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">Login<span id="login-button" class="glyphicon glyphicon-log-in"></span></a>
                <div class="dropdown-menu">
                    {% include 'toggle_login.html' %}
                </div>
               </li>
              <li><a href= "/accounts/register/">Register</a></li>
              {% endif %}
          </ul>
        </div>
      </div>
</nav>

templates/toggle_login.html
{% if form.errors %}
    <p>Your username and password didn't match. Please try again.</p>
{% endif %}

<form id="formLogin" class="form container-fluid" method="post" action="/accounts/login/">
    {% csrf_token %}
    <div class='form-group'>
        <input type='text' class='form-control' name='username' placeholder='Username'/>
    </div>

    <div class='form-group'>
        <input type='password' class='form-control' name='password' placeholder='Password'/>
    </div>

    <button type="submit" class='btn btn-secondary'>Login</button>

</form>